version: '3.7'

services:
    database:
        image: 'mariadb:10.6'
        environment:
            MYSQL_ROOT_PASSWORD: main
            MYSQL_DATABASE: main
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
