version: '3'

services:
    database:
        image: postgres:12
        environment:
            POSTGRES_DB: main
            POSTGRES_PASSWORD: main
            POSTGRES_USER: main
        volumes:
            - db-data:/var/lib/postgresql/data:rw

volumes:
    db-data:
