- name: Set HTTPDUSER
  shell: "ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d ' ' -f1"
  register: httpduser

- set_fact:
    httpd_user: "{{ httpduser.stdout }}"

- name: Setting up File Permissions for "var" (future files and folders)
  command: "setfacl -dR -m u:{{ httpd_user }}:rwX -m u:{{ ansible_user }}:rwX var"
  args:
      chdir: "{{ ansistrano_release_path.stdout }}"

- name: Setting up File Permissions for "var"
  command: "setfacl -R -m u:{{ httpd_user }}:rwX -m u:{{ ansible_user }}:rwX var"
  args:
      chdir: "{{ ansistrano_release_path.stdout }}"
